<?php
/** @var $block SamedayCourier\Shipping\Block\Adminhtml\Awb\Buttons */
?>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?php echo __('Sameday Courier') ?></span>
    </div>
    <div class="admin__page-section-content">
        <button type="button" onClick="setLocation('<?php echo $block->getAwbUrl(); ?>');">
            <?php echo __('Generează AWB'); ?>
        </button>
    </div>
</section>
