<?php
/** @var $block Form */
use SamedayCourier\Shipping\Block\Adminhtml\Awb\Form;

$orderDetails = $block->getOrderDetails() ?: [];
?>

<section class="admin__page-section">
    <div class="admin__page-section-content">
        <div class="admin__page-section-item">
            <section class="admin__page-section sameday-courier-section">
                <form action="<?= $block->escapeUrl($block->getRouteAddAwb()) ?>"
                      method="post"
                      id="sameday-add-awb-form"
                      class="samedaycourier_shipping_generate_awb_form">
                    <input type="hidden"
                           id="changeLockerUrl"
                           data-change_locker_url="<?= $block->escapeUrl($orderDetails['changeLockerMethodUrl'] ?? '') ?>">
                    <input type="hidden"
                           name="order_id"
                           value="<?= $block->escapeHtmlAttr($block->getOrder()->getId()) ?>">
                    <div class="row">
                        <div class="col-25">
                            <label for="repayment">
                                <?= $block->escapeHtml(__('Repayment')) ?>
                                <span style="font-weight: bolder">
                                    (<?= $block->escapeHtml($orderDetails['currency'] ?? '') ?>)
                                </span>
                            </label>
                        </div>
                        <div class="col-75">
                            <input name="repayment"
                                   id="repayment"
                                   type="number"
                                   step="any"
                                   min="0"
                                   value="<?= $block->escapeHtmlAttr($orderDetails['repayment'] ?? '') ?>">
                            <?php if (!empty($orderDetails['currencyWarningMessage'])): ?>
                                <span style="font-weight: bolder; color: #9f0101">
                                    <?= $block->escapeHtml($orderDetails['currencyWarningMessage']) ?>
                                </span>
                            <?php endif; ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-25">
                            <label for="insured_value">
                                <?= $block->escapeHtml(__('Insured value')) ?>
                            </label>
                        </div>
                        <div class="col-75">
                            <input name="insured_value" id="insured_value" type="number" step="any" min="0" value="0">
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-25">
                            <?= $block->escapeHtml(__('Package type')) ?>
                        </div>
                        <div class="col-75">
                            <select name="package_type" id="package_type">
                                <option value="0"><?= $block->escapeHtml(__('Parcel')) ?></option>
                                <option value="1"><?= $block->escapeHtml(__('Envelope')) ?></option>
                                <option value="2"><?= $block->escapeHtml(__('Large parcel')) ?></option>
                            </select>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-25">
                            <label for="packages" style="font-weight: bolder">
                                <?= $block->escapeHtml(__('Nr. of Packages')) ?>
                            </label>
                        </div>
                        <div class="col-75">
                            <input name="packages"
                                   title="<?= $block->escapeHtmlAttr(__('Use up/down buttons in order to add/remove packages')) ?>"
                                   pattern="^[0-9]"
                                   id="packages"
                                   type="number"
                                   step="1"
                                   min="1"
                                   value="1"
                                   style="font-weight: bolder">
                        </div>
                    </div>

                    <div class="row" id="package_dimensions">
                        <div class="package_dimensions_fields">
                            <div class="col-25">
                                <label for="package_weight">
                                    <?= $block->escapeHtml(__('Package dimensions')) ?>
                                </label>
                            </div>
                            <div class="col-75">
                                <div class="col-25">
                                    <input name="package_weight[]"
                                           id="package_weight"
                                           type="number"
                                           step="any"
                                           min="0"
                                           value="<?= $block->escapeHtmlAttr($orderDetails['weight'] ?? '') ?>">
                                </div>
                                <div class="col-25">
                                    <input name="package_length[]"
                                           id="package_length"
                                           type="number"
                                           step="any"
                                           min="0"
                                           placeholder="<?= $block->escapeHtmlAttr(__('length')) ?>">
                                </div>
                                <div class="col-25">
                                    <input name="package_width[]"
                                           id="package_width"
                                           type="number"
                                           step="any"
                                           min="0"
                                           placeholder="<?= $block->escapeHtmlAttr(__('width')) ?>">
                                </div>
                                <div class="col-25">
                                    <input name="package_height[]"
                                           id="package_height"
                                           type="number"
                                           step="any"
                                           min="0"
                                           placeholder="<?= $block->escapeHtmlAttr(__('height')) ?>">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-25">
                            <?= $block->escapeHtml(__('Service')) ?>
                        </div>
                        <div class="col-75">
                            <select name="service" id="service">
                                <?php foreach ($block->getServices() as $service): ?>
                                    <?php
                                    $isSelected = ($service->getCode() === ($orderDetails['serviceCode'] ?? ''));
                                    ?>
                                    <option
                                        data-service_code="<?= $block->escapeHtmlAttr($service->getCode()) ?>"
                                        data-service_locker_to_show="<?= $block->escapeHtmlAttr(
                                            $block->toggleHtmlElement($block->isEligibleToLocker($service->getCode()))
                                        ) ?>"
                                        data-service_eligible_locker_first_mile="<?= $block->escapeHtmlAttr(
                                            $block->toggleHtmlElement(
                                                $block->isServiceEligibleToLockerFirstMile($service->getCode())
                                            )
                                        ) ?>"
                                        value="<?= $block->escapeHtmlAttr($service->getSamedayId()) ?>"
                                        <?= $isSelected ? 'selected="selected"' : '' ?>
                                    >
                                        <?= $block->escapeHtml($service->getSamedayName()) ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>

                    <div id="showLockerFirstMile"
                         style="display: <?= $block->escapeHtmlAttr($orderDetails['displayLockerFirstMile'] ?? 'none') ?>">
                        <div class="row">
                            <div class="col-25"
                                 title="<?= $block->escapeHtmlAttr(__(
                                     'Check this field if you want to apply for Personal delivery of the package at an easyBox terminal.'
                                 )) ?>"
                                 style="cursor: help">
                                <?= $block->escapeHtml(__('Personal delivery at locker')) ?>
                                <span>
                                    <a href="https://sameday.ro/easybox#lockers-intro" target="_blank">
                                        <?= $block->escapeHtml(__('Show on map')) ?>
                                    </a>
                                </span>
                            </div>
                            <div class="col-75">
                                <input type="checkbox"
                                       name="locker_first_mile"
                                       class="checkbox"
                                       value="<?= $block->escapeHtmlAttr($orderDetails['serviceTaxCodePDO'] ?? '') ?>"
                                       id="lockerFirstMile">
                            </div>
                            <div class="col-75">
                                <div class="tooltip"><?= $block->escapeHtml(__('Show locker dimensions box')) ?>
                                    <span class="tooltiptext">
                                        <table class="data-grid data-grid-draggable">
                                            <tr>
                                                <th></th>
                                                <th style="text-align: center;">L</th>
                                                <th style="text-align: center;">l</th>
                                                <th style="text-align: center;">h</th>
                                            </tr>
                                            <tr>
                                                <td>Small (cm)</td><td>47</td><td>44.5</td><td>10</td>
                                            </tr>
                                            <tr>
                                                <td>Medium (cm)</td><td>47</td><td>44.5</td><td>19</td>
                                            </tr>
                                            <tr>
                                                <td>Large (cm)</td><td>47</td><td>44.5</td><td>39</td>
                                            </tr>
                                        </table>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div id="showLockerDetails"
                         style="display: <?= $block->escapeHtmlAttr($orderDetails['displayLockerDetails'] ?? 'none') ?>">
                        <div class="row">
                            <div class="col-25"
                                 title="<?= $block->escapeHtmlAttr(__('Delivery point for customer')) ?>">
                                <strong><?= $block->escapeHtml(__('Location details (Last Mile)')) ?></strong>
                            </div>
                            <div class="col-75">
                                <textarea disabled="disabled" id="lockerId_details" style="height:50px"><?= $block->escapeHtml(
                                    $orderDetails['samedaycourier_locker'] ?? ''
                                ) ?></textarea>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-25">
                                <span></span>
                            </div>
                            <div class="col-75">
                                <button type="button"
                                        id="changeLocker"
                                        name="changeLocker"
                                        data-country_code="<?= $block->escapeHtmlAttr($orderDetails['country-code'] ?? '') ?>"
                                        data-api_username="<?= $block->escapeHtmlAttr($orderDetails['api-username'] ?? '') ?>"
                                        data-city="<?= $block->escapeHtmlAttr($orderDetails['city'] ?? '') ?>"
                                        class="action-default scalable sameday-primary">
                                    <?= $block->escapeHtml(__('Change location')) ?>
                                </button>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-25">
                            <?= $block->escapeHtml(__('Pickup point')) ?>
                        </div>
                        <div class="col-75">
                            <select name="pickup_point" id="pickup_point">
                                <?php foreach ($block->getPickupPoints() as $pickupPoint): ?>
                                    <option value="<?= $block->escapeHtmlAttr($pickupPoint->getSamedayId()) ?>"
                                        <?= ((bool) $pickupPoint->getIsDefault()) === true ? 'selected="selected"' : '' ?>>
                                        <?= $block->escapeHtml($pickupPoint->getSamedayAlias()) ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-25">
                            <?= $block->escapeHtml(__('Awb payment')) ?>
                        </div>
                        <div class="col-75">
                            <select name="awb_payment" id="awb_payment">
                                <option value="0"><?= $block->escapeHtml(__('Client')) ?></option>
                            </select>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-25">
                            <label for="observation">
                                <?= $block->escapeHtml(__('Observation')) ?>
                            </label>
                        </div>
                        <div class="col-75">
                            <textarea name="observation"
                                      id="observation"
                                      placeholder="<?= $block->escapeHtmlAttr(__('Write something...')) ?>"
                                      style="height:50px"></textarea>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-25">
                            <label for="client_reference">
                                <?= $block->escapeHtml(__('Client Reference')) ?>
                            </label>
                        </div>
                        <div class="col-75">
                            <input type="text"
                                   name="client_reference"
                                   id="client_reference"
                                   value="<?= $block->escapeHtmlAttr($orderDetails['client_reference'] ?? '') ?>"
                                   placeholder="<?= $block->escapeHtmlAttr(__('Default value is order ID...')) ?>"
                                   style="height:50px">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-75">
                            <button type="submit"
                                    name="sameday-add-awb-form-submit"
                                    form="sameday-add-awb-form"
                                    class="edit sameday-primary"
                                    id="sameday-add-awb-form-submit"
                                    style="height:50px">
                                <?= $block->escapeHtml(__('Generate Awb')) ?>
                            </button>
                        </div>
                    </div>
                </form>
            </section>
        </div>
    </div>
</section>
