<?php
/** @var $block Form */
use SamedayCourier\Shipping\Block\Adminhtml\Awb\Form;
?>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"> Awb Form </span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item">
            <section class="admin__page-section sameday-courier-section">
                <form action="<?= $block->escapeUrl($block->getRouteAddAwb())?>" method="post" id="popup-add-awb-form" class="samedaycourier_shipping_generate_awb_form">
                    <input type="hidden" id="changeLockerUrl" data-change_locker_url="<?php echo $block->escapeUrl($block->getOrderDetails()['changeLockerMethodUrl']); ?>">
                    <div class="row">
                        <div class="col-25">
                            <label for="repayment">
                                <?= __('Repayment') ?>
                                <span style="font-weight: bolder"> (<?php echo $block->getOrderDetails()['currency']; ?>) </span>
                            </label>
                        </div>
                        <div class="col-75">
                            <input name="repayment" id="repayment" type="number" step="any" min="0" value="<?= $block->getOrderDetails()['repayment'] ?>">
                            <?php if (isset($block->getOrderDetails()['currencyWarningMessage'])) { ?>
                                <span style="font-weight: bolder; color: #9f0101">
                            <?php echo $block->getOrderDetails()['currencyWarningMessage']; ?>
                        </span>
                            <?php } ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-25">
                            <label for="insured_value">
                                <?= __('Insured value') ?>
                            </label>
                        </div>
                        <div class="col-75">
                            <input name="insured_value" id="insured_value" type="number" step="any" min="0" value="0">
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-25">
                            <?= __('Package type') ?>
                        </div>
                        <div class="col-75">
                            <select name="package_type" id="package_type">
                                <option value="0"><?= __('Parcel') ?></option>
                                <option value="1"><?= __('Envelope') ?></option>
                                <option value="2"><?= __('Large parcel') ?></option>
                            </select>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-25">
                            <label for="packages" style="font-weight: bolder">
                                <?= __('Nr. of Packages') ?>
                            </label>
                        </div>
                        <div class="col-75">
                            <input name="packages" title="Use up/down buttons in order to add/remove packages" pattern="^[0-9]" id="packages" type="number" step="1" min="1" value="1" style="font-weight: bolder">
                        </div>
                    </div>

                    <div class="row" id="package_dimensions">
                        <div class="package_dimensions_fields">
                            <div class="col-25">
                                <label for="insured_value">
                                    <?= __('Package dimensions') ?>
                                </label>
                            </div>
                            <div class="col-75">
                                <div class="col-25">
                                    <input name="package_weight[]" id="package_weight" type="number" step="any" min="0" value="<?= $block->getOrderDetails()['weight'] ?>">
                                </div>
                                <div class="col-25">
                                    <input name="package_length[]" id="package_length" type="number" step="any" min="0" placeholder="length">
                                </div>
                                <div class="col-25">
                                    <input name="package_width[]" id="package_width" type="number" step="any" min="0" placeholder="width">
                                </div>
                                <div class="col-25">
                                    <input name="package_height[]" id="package_height" type="number" step="any" min="0" placeholder="height">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-25">
                            <?= __('Service') ?>
                        </div>
                        <div class="col-75">
                            <select name="service" id="service">
                                <?php foreach ($block->getServices() as $service): ?>
                                    <option
                                        data-service_code="<?php echo $service->getCode();?>"
                                        data-service_locker_to_show="<?php echo $block->toggleHtmlElement($block->isEligibleToLocker($service->getCode())); ?>"
                                        data-service_eligible_locker_first_mile="<?php echo $block->toggleHtmlElement($block->isServiceEligibleToLockerFirstMile($service->getCode())); ?>"
                                        value="<?= $service->getSamedayId() ?>" <?= $service->getCode() === $block->getOrderDetails()['serviceCode'] ? 'selected' : '' ?>
                                    >
                                        <?= $service->getSamedayName() ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>

                    <div id="showLockerFirstMile" style="display: <?php echo $block->getOrderDetails()['displayLockerFirstMile']; ?>">
                        <div class="row">
                            <div class="col-25" title="<?php echo __('Check this field if you want to apply for Personal delivery of the package at an easyBox terminal.'); ?>" style="cursor: help">
                                <?= __('Personal delivery at locker') ?>
                                <span><a href="https://sameday.ro/easybox#lockers-intro" target="_blank"><?php echo __('Show on map')?></a></span>
                            </div>
                            <div class="col-75">
                                <input type="checkbox" name="locker_first_mile" class="checkbox" value="<?php echo $block->getOrderDetails()['serviceTaxCodePDO']; ?>" id="lockerFirstMile">
                            </div>
                            <div class="col-75">
                                <div class="tooltip"><?php echo __('Show locker dimensions box');?>
                                    <span class="tooltiptext">
                                <table class="data-grid data-grid-draggable"> <tr> <th></th> <th style="text-align: center;">L</th> <th style="text-align: center;">l</th> <th style="text-align: center;">h</th> </tr><tr> <td>Small (cm)</td><td> 47</td><td> 44.5</td><td> 10</td></tr><tr> <td>Medium (cm)</td><td> 47</td><td> 44.5</td><td> 19</td></tr><tr> <td>Large (cm)</td><td> 47</td><td> 44.5</td><td> 39</td></tr></table>
                            </span>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div id="showLockerDetails" style="display: <?php echo $block->getOrderDetails()['displayLockerDetails']; ?>">
                        <div class="row">
                            <div class="col-25" title="<?php echo __('Delivery point for customer');?>">
                                <strong> <?= __('Location details (Last Mile)') ?> </strong>
                            </div>
                            <div class="col-75">
                                <textarea disabled="disabled" id="lockerId_details" style="height:50px"><?php print $block->getOrderDetails()['samedaycourier_locker']; ?></textarea>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-25">
                                <span></span>
                            </div>
                            <div class="col-75">
                                <button type="button"
                                        id="changeLocker"
                                        name="changeLocker"
                                        data-country_code="<?php print $block->getOrderDetails()['country-code']; ?>"
                                        data-api_username="<?php print $block->getOrderDetails()['api-username']; ?>"
                                        data-city="<?php print $block->getOrderDetails()['city']; ?>"
                                        class="action-default scalable sameday-primary"
                                >
                                    <?= __('Change location') ?>
                                </button>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-25">
                            <?= __('Pickup point') ?>
                        </div>
                        <div class="col-75">
                            <select name="pickup_point" id="pickup_point">
                                <?php foreach ($block->getPickupPoints() as $pickupPoint): ?>
                                    <option value="<?= $pickupPoint->getSamedayId() ?>" <?= ((bool) $pickupPoint->getIsDefault()) === true ? 'selected' : '' ?>>
                                        <?= $pickupPoint->getSamedayAlias() ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-25">
                            <?= __('Awb payment') ?>
                        </div>
                        <div class="col-75">
                            <select name="awb_payment" id="awb_payment">
                                <option value="0"><?= __('Client')?></option>
                            </select>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-25">
                            <label for="subject">
                                <?= __('Observation') ?>
                            </label>
                        </div>
                        <div class="col-75">
                            <textarea name="observation" id="observation" placeholder="<?= __('Write something...') ?>" style="height:50px"></textarea>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-25">
                            <label for="subject">
                                <?= __('Client Reference') ?>
                            </label>
                        </div>
                        <div class="col-75">
                            <input type="text" name="client_reference" id="client_reference" value="<?= $block->getOrderDetails()['client_reference']; ?>" placeholder="<?= __('Default value is order ID...') ?>" style="height:50px">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-75">
                            <button type="submit" name="client_reference" class="edit sameday-primary" id="client_reference" style="height:50px"> Generate Awb</button>
                        </div>
                    </div>
                </form>
            </section>
        </div>
    </div>
</section>
