<?php
/** @var $block History */
use SamedayCourier\Shipping\Block\Adminhtml\Awb\History;
?>

<section class="admin__page-section">
    <div class="admin__page-section-content">
        <div class="admin__page-section-item">
            <section class="admin__page-section sameday-courier-section">

                Afisez istoricul awb-urilor

            </section>
        </div>
    </div>
</section>
