<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"> Awb Form </span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item">
            <section class="admin__page-section sameday-courier-section">
                <h1>
                    <?php echo __('Aici va fi afisat formularul de generare AWB'); ?>
                </h1>
            </section>
        </div>
    </div>
</section>
