<?php
/** @var $block Form */
use SamedayCourier\Shipping\Block\Adminhtml\Awb\Parcel\Form;
?>

<section class="admin__page-section">
    <div class="admin__page-section-content">
        <div class="admin__page-section-item">
            <section class="admin__page-section sameday-courier-section">

                Afisez formularul de adaugare pacel nou

            </section>
        </div>
    </div>
</section>
