<?php
/**
 * @var $block \SamedayCourier\Shipping\Block\Adminhtml\Order\SamedayModal
 */
?>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?php /* @escapeNotVerified */ echo __('Sameday Courier') ?></span>
    </div>
    <div class="admin__page-section-content">
        <button id="openmodal"><?= __('Generate awb') ?></button>
    </div>
</section>

<div id="popup-add-awb" style="display: none">
    <form action="<?= $block->escapeUrl($block->getRouteAddAwb())?>" method="post"
          id="popup-add-awb-form">
        <?= __('Repayment') ?> <input name="repayment" type="text" value="<?= $block->getOrderDetails()['repayment'] ?>"> <br />
        <?= __('Insured value') ?> <input name="insured_value" type="number" value="0"> <br />
        <?= __('Package weight') ?> <input name="package_weight" type="number" value="<?= $block->getOrderDetails()['weight'] ?>"> <br />
        <?= __('Package length') ?> <input name="package_length" type="number"> <br />
        <?= __('Package width') ?> <input name="package_width" type="number"> <br />

        <?= __('Pickup point') ?>
        <select name="pickup_point">
            <?php foreach ($block->getPickupPoints() as $pickupPoint): ?>
                <option value="<?= $pickupPoint->getSamedayId() ?>"><?= $pickupPoint->getSamedayAlias() ?></option>
             <?php endforeach; ?>
        </select>

        <br />

        <?= __('Package type') ?>
        <select name="package_type">
            <option value="0"><?= _('Parcel') ?></option>
            <option value="1"><?= _('Envelope') ?></option>
        </select>

        <br />

        <?= __('Awb payment') ?>
        <select name="awb_payment">
            <option value="0"><?= _('Client')?></option>
        </select>

        <br />

        <?= __('Service') ?>
        <select name="service">
            <?php foreach ($block->getServices() as $service): ?>
                <option value="<?= $service->getSamedayId() ?>"><?= $service->getSamedayName() ?></option>
            <?php endforeach; ?>
        </select>

        <br />

        <?= __('Open package') ?> <input name="open_package" type="checkbox" value="1"> <br />
        <?= __('Observation') ?> <textarea name="observation"></textarea> <br />
        <input type="hidden" name="order_id" value="<?= $block->getOrder()->getId() ?>">

        <input type="button" value="Submit" id="order-view-add-warranty"> <br />
    </form>
</div>

<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function (
            $,
            modal
        ) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'Generate awb',
                modalClass: 'custom-modal',
                buttons: [{
                    text: $.mage.__('Close'),
                    class: '',
                    click: function () {
                        this.closeModal();
                    }
                }]
            };

            var popup = modal(options, $('#popup-add-awb'));
            $("#openmodal").click(function() {
                $("#popup-add-awb").modal('openModal');
            });

            $('#popup-add-awb-form').click(function () {
                $('#popup-add-awb-form').append($('<input>', {
                    'name': 'form_key',
                    'value': window.FORM_KEY,
                    'type': 'hidden'
                }));
                $('#popup-add-awb-form').submit();
            });
        }
    );
</script>