<?php
/**
 * @var $block \SamedayCourier\Shipping\Block\Adminhtml\Order\SamedayModal
 */
$awb = $block->getData('awb');

/** @var \Sameday\Responses\SamedayGetAwbStatusHistoryResponse $awbHistory */
$parcelsHistory = $block->getData('parcelsHistory');
?>

<style>
    * {
        box-sizing: border-box;
    }

    input[type=text], select, textarea {
        width: 100%;
        padding: 12px;
        border: 1px solid #ccc;
        resize: vertical;
    }

    input[type=number], select, textarea {
        width: 100%;
        padding: 12px;
        border: 1px solid #ccc;
        resize: vertical;
    }

    label {
        padding: 12px 12px 12px 0;
        display: inline-block;
    }

    input[type=submit] {
        background-color: #41362f;
        color: white;
        padding: 12px 20px;
        border: none;
        cursor: pointer;
        float: right;
    }

    input[type=submit]:hover {
        background-color: #41362f;
    }

    .container {
        border-radius: 5px;
        background-color: #f2f2f2;
        padding: 20px;
    }

    .col-25 {
        float: left;
        width: 25%;
        margin-top: 6px;
    }

    .col-75 {
        float: left;
        width: 75%;
        margin-top: 6px;
    }

    /* Clear floats after the columns */
    .row:after {
        content: "";
        display: table;
        clear: both;
    }

    .packages {
        font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }

    .packages td, .packages th {
        border: 1px solid #ddd;
        padding: 8px;
    }

    .packages tr:nth-child(even){background-color: #f2f2f2;}

    .packages tr:hover {background-color: #FFFFFE;}

    .packages th {
        padding-top: 14px;
        padding-bottom: 14px;
        text-align: left;
        background-color: #f1f1f1;
        color: #41362f;
    }

    .history {
        font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
        border-collapse: collapse;
        width: auto;
    }

    .history td, .history th {
        border: 1px solid #ddd;
        padding: 8px;
    }

    .history tr:nth-child(even){background-color: #f2f2f2;}

    .history tr:hover {background-color: #FFFFFE;}

    .history th {
        padding-top: 10px;
        padding-bottom: 10px;
        text-align: left;
        background-color: #41362f;
        color: #FFFFFE;
    }

    /* Responsive layout - when the screen is less than 600px wide, make the two columns stack on top of each other instead of next to each other */
    @media screen and (max-width: 600px) {
        .col-25, .col-75, input[type=submit] {
            width: 100%;
            margin-top: 0;
        }
    }
</style>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?php /* @escapeNotVerified */ echo __('Sameday Courier') ?></span>
    </div>
    <div class="admin__page-section-content">
        <button id="add_parcel_modal"><?= __('Add new parcel') ?></button>
        <button id="awb_history_modal"><?= __('Awb history') ?></button>
        <a href="<?= $block->escapeUrl($block->getRouteAwbAsPdf())?>"><?= __('Show as pdf') ?></a>
        <button id="remove_awb"><?= __('Remove Awb') ?></button>
        <a target="_blank" href="https://eawb.sameday.ro/awb?awbOrParcelNumber=<?= $awb->getAwbNumber() ?>&tab=allAwbs"><?= __('Sameday eAwb') ?></a>
    </div>
</section>

<?php
/**
 * Add parcel modal
 */
?>
<div id="popup-add-parcel" style="display: none">
    <div class="container">
        <form action="<?= $block->escapeUrl($block->getRouteAddParcel())?>" method="post" id="popup-add-parcel-form">
        <div class="row">
            <div class="col-25">
                <label for="repayment">
                    <?= __('Parcel weight') ?>
                </label>
            </div>
            <div class="col-75">
                <input name="parcel_weight" type="number" value="1" step="any" min="0">
            </div>
        </div>
        <div class="row">
            <div class="col-25">
                <label for="repayment">
                    <?= __('Parcel length') ?>
                </label>
            </div>
            <div class="col-75">
                <input name="parcel_length" type="number" step="any" min="0">
            </div>
        </div>
        <div class="row">
            <div class="col-25">
                <label for="repayment">
                    <?= __('Parcel height') ?>
                </label>
            </div>
            <div class="col-75">
                <input name="parcel_height" type="number" step="any" min="0">
            </div>
        </div>
        <div class="row">
            <div class="col-25">
                <label for="repayment">
                    <?= __('Parcel width') ?>
                </label>
            </div>
            <div class="col-75">
                <input name="parcel_width" type="number" step="any" min="0">
            </div>
        </div>
    </form>
    </div>
</div>

<?php
/**
 * Awb history modal
 */
?>
<div id="popup-awb-history" style="display: none">

    <?php
        $packageRows = '';

        foreach ($parcelsHistory as $package) {
            $summary = $package->getSummary();
            $packageHistory = $package->getHistory();
            $historyRows = '';
            foreach ($packageHistory as $history) {
                $historyRows .=
                    '<td>' . $history->getName() . '</td>' .
                    '<td>' . $history->getLabel() . '</td>' .
                    '<td>' . $history->getState() . '</td>' .
                    '<td>' . $history->getDate()->format('Y-m-d H:i:s') . '</td>' .
                    '<td>' . $history->getCounty() . '</td>' .
                    '<td>' . $history->getTransitLocation() . '</td>' .
                    '<td>' . $history->getReason() . '</td>'
                ;
            }
            $packageRows .=
                '<tr>' .
                    '<td style="text-align: center; cursor:pointer;" class="showHistoryDetails" value="-" data-awb-number="'.$summary->getParcelAwbNumber().'"> <strong> + </strong> </td>' .
                    '<td>' . $summary->getParcelAwbNumber() . '</td>' .
                    '<td>' . $summary->getParcelWeight() . '</td>' .
                    '<td>' . ($summary->isDelivered() ? "Yes" : "No") . '</td>' .
                    '<td>' . $summary->getDeliveryAttempts() . ' </td>' .
                    '<td>' . ($summary->isPickedUp() ? 'Yes' : 'No') . '</td>' .
                    '<td>' . ($summary->getPickedUpAt() ? $summary->getPickedUpAt()->format('Y-m-d H:i:s') : '') .'</td>' .
                '</tr>' .
                '<tr>' .
                    '<td colspan="7">' .
                        '<table class="history" id="history-'.$summary->getParcelAwbNumber().'" style="width: 100%; display: none; text-align: center">' .
                            '<tr>' .
                                '<th style="width: 15%">' . __("Status") . '</th>' .
                                '<th style="width: 15%">' . __("Label") . '</th>' .
                                '<th style="width: 15%">' . __("State") . '</th>' .
                                '<th style="width: 15%">' . __("Date") . '</th>' .
                                '<th style="width: 15%">' . __("County") . '</th>' .
                                '<th style="width: 15%">' . __("Translation") . '</th>' .
                                '<th style="width: 15%">' . __("Reason") . '</th>' .
                            '</tr>' .
                            $historyRows .
                        '</table>' .
                    '</td>' .
                '</tr>'


            ;
        }
    ?>
    <table class="packages" style="width: 100%">
        <tr>
            <th></th>
            <th scope="col"><?= __('Parcel number') ?></th>
            <th scope="col"><?= __('Parcel weight') ?></th>
            <th scope="col"><?= __('Delivered') ?></th>
            <th scope="col"><?= __('Delivery attempts') ?></th>
            <th scope="col"><?= __('Is picked up') ?></th>
            <th scope="col"><?= __('Picked up at') ?></th>
        </tr>
        <?= $packageRows ?>
    </table>
</div>

<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal',
            'Magento_Ui/js/modal/confirm'
        ],
        function ($, modal, confirmation) {
            $("#add_parcel_modal").click(function() {
                var options = {
                    type: 'popup',
                    responsive: true,
                    innerScroll: true,
                    title: 'Add parcel',
                    modalClass: 'custom-modal',
                    buttons: [
                        {
                            text: $.mage.__('Close'),
                            class: '',
                            click: function () {
                                this.closeModal();
                            }
                        },
                        {
                            text: $.mage.__('Add parcel'),
                            class: '',
                            click: function () {
                                $('#popup-add-parcel-form').submit();
                            }
                        }
                    ]
                };

                var popup = modal(options, $('#popup-add-parcel'));
                $("#popup-add-parcel").modal('openModal');
            });

            $('#popup-add-parcel-form').click(function () {
                $('#popup-add-parcel-form').append($('<input>', {
                    'name': 'form_key',
                    'value': window.FORM_KEY,
                    'type': 'hidden'
                }));
            });

            $(document).on("click", ".showHistoryDetails", function() {
                let show = $(this).val();
                let awbNumber = $(this).data("awb-number");
                let table_id = "history-" + awbNumber;
                if (show === "+") {
                    $("#"+table_id).css("display","block");
                    $(this).val("-");
                    $(this).html("<strong> - </strong>");
                } else {
                    $("#"+table_id).css("display","none");
                    $(this).val("+");
                    $(this).html("<strong> + </strong>");
                }
            });

            $(".showHistoryDetails").trigger("click");

            // awb history
            $("#awb_history_modal").click(function() {
                var options = {
                    type: 'popup',
                    responsive: true,
                    innerScroll: true,
                    title: 'Awb history',
                    modalClass: 'custom-modal',
                    buttons: [{
                        text: $.mage.__('Close'),
                        class: '',
                        click: function () {
                            this.closeModal();
                        }
                    }]
                };

                var popup = modal(options, $('#popup-awb-history'));
                $("#popup-awb-history").modal('openModal');
            });

            // remove awb
            $("#remove_awb").click(function() {
                confirmation({
                    title: $.mage.__('Remove awb confirmation'),
                    content: $.mage.__('Are you sure you want to remove this awb?'),
                    actions: {
                        confirm: function() {
                            let param = {
                                "form_key": window.FORM_KEY,
                                "awb_id": <?= $awb->getId() ?>,
                                "sameday_awb_number": "<?= $awb->getAwbNumber() ?>"
                            }

                            $.ajax({
                                showLoader: true,
                                url: "<?= $block->escapeUrl($block->getRouteRemoveAwb()) ?>",
                                data: param,
                                type: "POST",
                                dataType: 'json'
                            }).done(function (data) {
                                location.reload();
                            });
                        }
                    }
                });
            });
        }
    );
</script>