<?php
/**
 * @var $block \SamedayCourier\Shipping\Block\Adminhtml\Order\SamedayModal
 */
$awb = $block->getData('awb');
?>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?php /* @escapeNotVerified */ echo __('Sameday Courier') ?></span>
    </div>
    <div class="admin__page-section-content">
        <button id="add_parcel_modal"><?= __('Add new parcel') ?></button>
        <button id="awb_history_modal"><?= __('Awb history') ?></button>
        <button><?= __('Show as pdf') ?></button>
        <button><?= __('Remove Awb') ?></button>
        <a target="_blank" href="https://eawb.sameday.ro/awb?awbOrParcelNumber=<?= $awb->getAwbNumber() ?>&tab=allAwbs"><?= __('Sameday eAwb') ?></a>
    </div>
</section>

<?php
/**
 * Add parcel modal
 */
?>

<div id="popup-add-parcel" style="display: none">
    <form action="<?= $block->escapeUrl($block->getRouteAddParcel())?>" method="post" id="popup-add-parcel-form">
        <?= __('Parcel weight') ?> <input name="weight" type="number" value="1"> <br />
        <?= __('Parcel length') ?> <input name="insured_value" type="number"> <br />
        <?= __('Package weight') ?> <input name="package_weight" type="number" value="<?= $block->getOrderDetails()['weight'] ?>"> <br />
        <?= __('Package length') ?> <input name="package_length" type="number"> <br />
        <?= __('Package width') ?> <input name="package_width" type="number"> <br />
        <input type="button" value="Add new parcel" id="order-view-add-warranty"> <br />
    </form>
</div>

<div id="popup-awb-history" style="display: none">
    <table>
        <thead>
            <tr>
                <th scope="col"><?= __('Parcel number') ?></th>
                <th scope="col"><?= __('Parcel weight') ?></th>
                <th scope="col"><?= __('Delivered') ?></th>
                <th scope="col"><?= __('Delivery attempts') ?></th>
                <th scope="col"><?= __('Is picked up') ?></th>
                <th scope="col"><?= __('Picked up at') ?></th>
            </tr>
        </thead>

    </table>
</div>

<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function (
            $,
            modal
        ) {
            $("#add_parcel_modal").click(function() {
                var options = {
                    type: 'popup',
                    responsive: true,
                    innerScroll: true,
                    title: 'Add parcel',
                    modalClass: 'custom-modal',
                    buttons: [{
                        text: $.mage.__('Close'),
                        class: '',
                        click: function () {
                            this.closeModal();
                        }
                    }]
                };

                var popup =   modal(options, $('#popup-add-parcel'));
                $("#popup-add-parcel").modal('openModal');
            });

            $('#popup-add-parcel-form').click(function () {
                $('#popup-add-parcel-form').append($('<input>', {
                    'name': 'form_key',
                    'value': window.FORM_KEY,
                    'type': 'hidden'
                }));
                $('#popup-add-parcel-form').submit();
            });

            // awb history
            $("#awb_history_modal").click(function() {
                var options = {
                    type: 'popup',
                    responsive: true,
                    innerScroll: true,
                    title: 'Awb history',
                    modalClass: 'custom-modal',
                    buttons: [{
                        text: $.mage.__('Close'),
                        class: '',
                        click: function () {
                            this.closeModal();
                        }
                    }]
                };

                var popup = modal(options, $('#popup-awb-history'));
                $("#popup-awb-history").modal('openModal');
            });
        }
    );
</script>