<?php
/** @var $block SamedaySection */
use SamedayCourier\Shipping\Block\Adminhtml\Order\SamedaySection;
?>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('SamedayCourier')) ?></span>
    </div>
    <div class="admin__page-section-content">
        <?php if ($block->orderHasAwb()): ?>
            <div class="admin__page-section-content">
                <button class="sameday-primary"
                        type="button"
                        id="add_parcel_modal"
                        onclick="setLocation('<?= $block->escapeUrl($block->goToAddNewParcelFormPage()) ?>')">
                    <?= $block->escapeHtml(__('Add new parcel')) ?>
                </button>
                <button class="sameday-primary"
                        id="awb_history_modal"
                        type="button"
                        onclick="setLocation('<?= $block->escapeUrl($block->goToAwbHistoryPage()) ?>')">
                    <?= $block->escapeHtml(__('Awb history')) ?>
                </button>
                <button class="sameday-primary"
                        type="button"
                        onclick="setLocation('<?= $block->escapeUrl($block->getRouteAwbAsPdf()) ?>')">
                    <?= $block->escapeHtml(__('Show as pdf')) ?>
                </button>
                <button class="sameday-primary"
                        id="remove_awb"
                        data-awb_id="<?= $block->escapeHtmlAttr($block->getAwb()->getId()) ?>"
                        data-sameday_awb_number="<?= $block->escapeHtmlAttr($block->getAwb()->getAwbNumber()) ?>"
                        data-remove_awb_url="<?= $block->escapeUrl($block->getRouteRemoveAwb()) ?>">
                    <?= $block->escapeHtml(__('Remove Awb')) ?>
                </button>

                <div id="popup_awb_history" style="display: none" class="samedaycourier_shipping_awb_history"></div>
            </div>
        <?php else: ?>
            <button class="edit sameday-primary"
                    type="button"
                    onclick="setLocation('<?= $block->escapeUrl($block->goToAwbFormPage()) ?>')">
                <?= $block->escapeHtml(__('Generate Sameday AWB')) ?>
            </button>
        <?php endif; ?>
    </div>
</section>
