<?php
/**
 * @var $block \SamedayCourier\Shipping\Block\Adminhtml\Order\SamedayModal
 */
?>
<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?php /* @escapeNotVerified */ echo __('Sameday Courier') ?></span>
    </div>
    <div class="admin__page-section-content">
        <button id="openmodal"><?= __('Generate awb') ?></button>
    </div>
</section>

<div id="popup-add-awb" style="display: none">
    <div class="container">
        <form action="<?= $block->escapeUrl($block->getRouteAddAwb())?>" method="post" id="popup-add-awb-form" class="samedaycourier_shipping_generate_awb_form">
            <input type="hidden" name="order_id" value="<?= $block->getOrder()->getId() ?>">
            <div class="row">
                <div class="col-25">
                    <label for="repayment">
                        <?= __('Repayment') ?>
                    </label>
                </div>
                <div class="col-75">
                    <input name="repayment" id="repayment" type="number" step="any" min="0" value="<?= $block->getOrderDetails()['repayment'] ?>">
                </div>
            </div>
            <div class="row">
                <div class="col-25">
                    <label for="insured_value">
                        <?= __('Insured value') ?>
                    </label>
                </div>
                <div class="col-75">
                    <input name="insured_value" id="insured_value" type="number" step="any" min="0" value="0">
                </div>
            </div>
            <div class="row">
                <div class="col-25">
                    <label for="package_weight">
                        <?= __('Package weight') ?>
                    </label>
                </div>
                <div class="col-75">
                    <input name="package_weight" id="package_weight" type="number" step="any" min="0" value="<?= $block->getOrderDetails()['weight'] ?>">
                </div>
            </div>
            <div class="row">
                <div class="col-25">
                    <label for="package_length">
                        <?= __('Package length') ?>
                    </label>
                </div>
                <div class="col-75">
                    <input name="package_length" id="package_length" type="number" step="any" min="0">
                </div>
            </div>
            <div class="row">
                <div class="col-25">
                    <label for="package_width">
                        <?= __('Package width') ?>
                    </label>
                </div>
                <div class="col-75">
                     <input name="package_width" id="package_width" type="number" step="any" min="0">
                </div>
            </div>
            <div class="row">
                <div class="col-25">
                    <label for="package_height">
                        <?= __('Package height') ?>
                    </label>
                </div>
                <div class="col-75">
                    <input name="package_height" id="package_height" type="number" step="any" min="0">
                </div>
            </div>
            <div class="row">
                <div class="col-25">
                    <?= __('Pickup point') ?>
                </div>
                <div class="col-75">
                    <select name="pickup_point" id="pickup_point">
                        <?php foreach ($block->getPickupPoints() as $pickupPoint): ?>
                            <option value="<?= $pickupPoint->getSamedayId() ?>" <?= $pickupPoint->getIsDefault() == 1 ? 'selected' : '' ?>>
                                <?= $pickupPoint->getSamedayAlias() ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
            <div class="row">
                <div class="col-25">
                    <?= __('Package type') ?>
                </div>
                <div class="col-75">
                    <select name="package_type" id="package_type">
                        <option value="0"><?= __('Parcel') ?></option>
                        <option value="1"><?= __('Envelope') ?></option>
                        <option value="2"><?= __('Large parcel') ?></option>
                    </select>
                </div>
            </div>
            <div class="row">
                <div class="col-25">
                    <?= __('Awb payment') ?>
                </div>
                <div class="col-75">
                    <select name="awb_payment" id="awb_payment">
                        <option value="0"><?= __('Client')?></option>
                    </select>
                </div>
            </div>
            <div class="row">
                <div class="col-25">
                    <?= __('Service') ?>
                </div>
                <div class="col-75">
                    <select name="service" id="service">
                        <?php foreach ($block->getServices() as $service): ?>
                            <option value="<?= $service->getSamedayId() ?>" <?= $service->getSamedayId() == $block->getOrderDetails()['serviceId'] ? 'selected' : '' ?>><?= $service->getSamedayName() ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
            <div class="row">
                <div class="col-25">
                    <label for="subject">
                        <?= __('Observation') ?>
                    </label>
                </div>
                <div class="col-75">
                    <textarea name="observation" id="observation" placeholder="<?= __('Write something...') ?>" style="height:50px"></textarea>
                </div>
            </div>
            <div class="row">
                <div class="col-25">
                    <label for="subject">
                        <?= __('Client Reference') ?>
                    </label>
                </div>
                <div class="col-75">
                    <input type="text" name="client_reference" id="client_reference" value="<?= $block->getOrderDetails()['client_reference']; ?>" placeholder="<?= __('Default value is order ID...') ?>" style="height:50px">
                </div>
            </div>
        </form>
    </div>
</div>

<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function (
            $,
            modal
        ) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'Generate awb',
                modalClass: 'custom-modal',
                buttons: [
                    {
                        text: $.mage.__('Close'),
                        class: '',
                        click: function () {
                            this.closeModal();
                        }
                    },
                    {
                        text: $.mage.__('Generate Awb'),
                        class: '',
                        click: function () {
                            $('#popup-add-awb-form').append($('<input>', {
                                'name': 'form_key',
                                'value': window.FORM_KEY,
                                'type': 'hidden'
                            }));
                            $('#popup-add-awb-form').submit();
                        }
                    }
                ]
            };

            var popup = modal(options, $('#popup-add-awb'));
            $("#openmodal").click(function() {
                $("#popup-add-awb").modal('openModal');
            });
        }
    );
</script>