<tr class="samedaycourier_locker_container">
    <td colspan="100" class="samedaycourier-lockers-wrapper">
        <label for="samedaycourier_shipping_lockers"><span><?= __('Please select a locker') ?></span></label>
        <select name='samedaycourier_locker' id="samedaycourier_shipping_lockers">
            <?php
            $options = '';
            foreach ($block['cities'] as $cityLockers => $lockers) {
                $options .= '<optgroup label="'. $cityLockers .'">';
                foreach ($lockers as $locker) {
                    $options .= sprintf('<option name="%s" value="%d">%s</option>', $locker['id'], $locker['id'], $locker['name']);
                }
                $options .= '</optgroup>';
            }
            ?>

            <?= $options; ?>
        </select>
    </td>
</tr>
